extends:
  ./config/index.yaml
env:
  node: true
rules:
  # Relax
  "@typescript-eslint/no-unsafe-member-access": off
  "@typescript-eslint/no-unsafe-assignment": off
  "@typescript-eslint/no-unsafe-argument": off
  "@typescript-eslint/no-require-imports": off

  # Nobody extends Object.prototype anymore
  guard-for-in: off
